### ISSUE TITLE
2.0.0-next.4 release checklist

### ISSUE THREAD

**Issue by 43081j** [runem/web-component-analyzer#236]
- [x] Merge #235 - Align typescript to the same version as lit-analyzer
- [x] Merge #233  - Resolve decorator config from variables (optional but nice to have)
- [x] Publish to npm

cc @justinfagnani @rictic

**Comment by rictic** [comment]
On it
